name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme ghp-import pytest sphinx_autodoc_typehints 
      - name: Build HTML
        run: |
          cd docs/
          make html
      - name: Run ghp-import
        run: |
          ghp-import -n -p -f docs/_build/html